# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(446, 418)
        MainWindow.setMouseTracking(True)
        MainWindow.setDocumentMode(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_corpo = QtWidgets.QFrame(self.widget)
        self.frame_corpo.setAcceptDrops(False)
        self.frame_corpo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_corpo.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_corpo.setObjectName("frame_corpo")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_corpo)
        self.gridLayout.setObjectName("gridLayout")
        self.entrada = QtWidgets.QLineEdit(self.frame_corpo)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        self.entrada.setFont(font)
        self.entrada.setWhatsThis("")
        self.entrada.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.entrada.setAutoFillBackground(True)
        self.entrada.setMaxLength(5)
        self.entrada.setFrame(True)
        self.entrada.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.entrada.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.entrada.setDragEnabled(False)
        self.entrada.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.entrada.setClearButtonEnabled(False)
        self.entrada.setObjectName("entrada")
        self.gridLayout.addWidget(self.entrada, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.frame_corpo)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label.setLineWidth(1)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 5)
        self.btn_limpeza = QtWidgets.QPushButton(self.frame_corpo)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        self.btn_limpeza.setFont(font)
        self.btn_limpeza.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_limpeza.setMouseTracking(True)
        self.btn_limpeza.setObjectName("btn_limpeza")
        self.gridLayout.addWidget(self.btn_limpeza, 4, 4, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 4, 3, 1, 1)
        self.btn_pesquisa = QtWidgets.QPushButton(self.frame_corpo)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        self.btn_pesquisa.setFont(font)
        self.btn_pesquisa.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_pesquisa.setMouseTracking(True)
        self.btn_pesquisa.setTabletTracking(True)
        self.btn_pesquisa.setAcceptDrops(False)
        self.btn_pesquisa.setToolTip("")
        self.btn_pesquisa.setToolTipDuration(0)
        self.btn_pesquisa.setCheckable(False)
        self.btn_pesquisa.setChecked(False)
        self.btn_pesquisa.setAutoDefault(True)
        self.btn_pesquisa.setDefault(False)
        self.btn_pesquisa.setFlat(False)
        self.btn_pesquisa.setObjectName("btn_pesquisa")
        self.gridLayout.addWidget(self.btn_pesquisa, 4, 1, 1, 2)
        self.table = QtWidgets.QTableView(self.frame_corpo)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        self.table.setFont(font)
        self.table.setTextElideMode(QtCore.Qt.ElideRight)
        self.table.setGridStyle(QtCore.Qt.SolidLine)
        self.table.setSortingEnabled(True)
        self.table.setObjectName("table")
        self.table.horizontalHeader().setCascadingSectionResizes(False)
        self.table.verticalHeader().setVisible(False)
        self.table.verticalHeader().setSortIndicatorShown(True)
        self.table.verticalHeader().setStretchLastSection(False)
        self.gridLayout.addWidget(self.table, 2, 0, 1, 5)
        self.line = QtWidgets.QFrame(self.frame_corpo)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 3, 0, 1, 5)
        self.line_2 = QtWidgets.QFrame(self.frame_corpo)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 1, 0, 1, 5)
        self.gridLayout_4.addWidget(self.frame_corpo, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.widget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.entrada.setPlaceholderText(_translate("MainWindow", "Digite o código da fazenda"))
        self.label.setText(_translate("MainWindow", "CHECAGEM DE VOOS"))
        self.btn_limpeza.setText(_translate("MainWindow", "Limpar"))
        self.btn_pesquisa.setText(_translate("MainWindow", "Procurar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

